OrberByForInscription
ETICINSATechnologies/Keros-Front pull request #127
Opened 2020-02-27 23:29 UTC by OrcaZ969

2020-02-27 23:33 UTC, OrcaZ969 commented
Dans la documentation fournie par le back il n'y a pas de select par departement et par wantedPole, donc j'ai pas inplémenté le dropdown select pour les inscriptions

2020-03-01 22:11 UTC, Arteox requested changes

2020-03-01 22:11 UTC, Arteox commented on tscommand-4dc2d19f.tmp.txt
> +src\config\Config.ts src\config\Environment.ts src\config\IConfig.ts src\control\auth\authRouter.ts src\control\auth\LoginController.ts src\control\auth\LogoutController.ts src\control\core\Consultan
c'est quoi ce fichier ?

2020-03-04 15:14 UTC, Arteox approved these changes

2020-03-04 15:14 UTC, merged