added alumni to member button
ETICINSATechnologies/Keros-Front pull request #157
Opened 2020-11-21 18:57 UTC by Arteox

2020-12-02 14:57 UTC, teckwan requested changes
if you can, please change the settings of your IDE, change tabs into spaces, and make each tab 2 spaces.

2020-12-02 18:31 UTC, Arteox commented
> if you can, please change the settings of your IDE, change tabs into spaces, and make each tab 2 spaces.

Ok will do !

2020-12-04 19:15 UTC, teckwan requested changes
Sorry I'm a little annoying, just trying to make everything consistent

2020-12-04 19:15 UTC, teckwan commented on views/partials/info-box/profile/buttons.hbs
> +      {{> modals/member}}
not a 2 space tab i think....

2020-12-04 19:15 UTC, teckwan commented on views/partials/modals/member.hbs
> +    <i class="fas fa-walking"></i>
here as well

2020-12-04 19:15 UTC, teckwan commented on views/partials/modals/member.hbs
> +        Êtes-vous sûr de vouloir passer l'ancien en membre ?
one tab here if possible

2020-12-08 13:14 UTC, merged