WIP - modif output if no member on study/no page left
ETICINSATechnologies/Keros-Front pull request #57
Opened 2019-02-12 10:25 UTC by vdevulder1

2019-02-12 10:39 UTC, ConorRyan requested changes

2019-02-12 10:39 UTC, ConorRyan commented on public/ajax/ajaxSelect.js
> +    return $(this).attr('name').match(/.*Id1$/) && $(this).attr('data-endpoint') === "/core/member";
Si je me trompe pas vous utilisez cette fonction pour les contacts et les membres, il me semble donc que tu peux pas hardcoder le `core/member`. @Pabl01  ?

2019-02-12 10:39 UTC, ConorRyan commented on public/ajax/ajaxSelect.js
> +    return $(this).attr('name').match(/.*Id1$/) && $(this).attr('data-endpoint') === "/core/member";
De plus, je comprend pas le `.match(/.*Id1$/)`, tu peux expliquer stp ?

2019-02-12 17:27 UTC, Pabl01 commented on public/ajax/ajaxSelect.js
> +    return $(this).attr('name').match(/.*Id1$/) && $(this).attr('data-endpoint') === "/core/member";
Tu as raison, c'est une fonction générique à tous car la du coup, seul les selects concernant les membres vont être affecté MAIS les responsables et les consultants sont tout deux des Member donc cela va bien ajouter le message "Aucun truc" sur les selects concernés par ça (je sais pas si je suis clair)

2019-02-12 17:28 UTC, Pabl01 commented on public/ajax/ajaxSelect.js
> +    return $(this).attr('name').match(/.*Id1$/) && $(this).attr('data-endpoint') === "/core/member";
Pour le `.match(/.*Id1$/)`, je pense qu'il a voulu cibler uniquement le premier Select d'une catégorie (responable, consultants...) pour afficher le message uniquement là (ça se tient)

2019-02-12 21:30 UTC, vdevulder1 commented on public/ajax/ajaxSelect.js
> +    return $(this).attr('name').match(/.*Id1$/) && $(this).attr('data-endpoint') === "/core/member";
Ouais, c'est exactement ça pour le `.match(/.*Id1$/)`, je me suis dit que normalement, le cas où il n'y a aucun membre ou responsable c'est si le premier champ est vide donc sur les autres ça ne sert à rien d'ajouter ce message.

2019-02-13 12:06 UTC, ConorRyan approved these changes

2019-02-13 12:06 UTC, merged