following of work on memberInscription
ETICINSATechnologies/Keros-Front pull request #73
Opened 2019-03-28 20:55 UTC by vdevulder1

2019-03-28 21:04 UTC, vdevulder1 commented on src/control/core/AuthenticateBackendController.ts
> +      winston.debug("Response from get req : ");
Modifs en raison de tests que j'avais effectué. J'ai pas fait gaffe avant de push, j'aurais du annuler les modifs. Mais comme on en a parlé ces fichiers seront amenés à être supprimés de toute façon.

2019-03-28 21:06 UTC, vdevulder1 commented on src/util/handlebars.ts
> -import { Study } from "../models/ua/Study";
C'était inutilisé

2019-03-28 21:07 UTC, vdevulder1 commented on views/sg/inscription/members/viewAll.hbs
> +  {{> template/sidebar}}
Aperçu : 
![visuelMembreInscriptionviewAll](https://user-images.githubusercontent.com/45464593/55192899-eaaa6500-51a5-11e9-98a0-61c7d3895c8e.PNG)

2019-03-28 21:15 UTC, vdevulder1 commented on views/sg/inscription/members/viewInscription.hbs
> +                        <div class="panel panel-default">
Aperçu des docs : 

![VisuelMembreInscriptionDocuments](https://user-images.githubusercontent.com/45464593/55193333-f2b6d480-51a6-11e9-8353-ee7423e46e24.PNG)

2019-03-28 21:17 UTC, vdevulder1 commented on views/sg/inscription/members/viewInscription.hbs
> +                        <option value="{{id}}" {{selected id @root.inscription.nationality.id}}>{{label}}</option>
Aperçu : 

![visuelMemberInscriptionviewMember](https://user-images.githubusercontent.com/45464593/55193415-2a258100-51a7-11e9-9a3f-eeaa1711bcb5.PNG)

2019-04-02 20:48 UTC, ConorRyan requested changes
Du coup comme tu as modifié un fichier qui était enlevé dans l'autre MR et que j'ai merge l'autre, faudra rebase celui là :/
Si besoin, au cas où :
```
git checkout develop
git pull
git checkout memberSignUp
git rebase develop
//Gérer conflits
git add -A
git rebase --continue
git push -f
```

2019-04-03 08:13 UTC, vdevulder1 commented
Voilà j'ai rebase. Si tout est bon pour toi il reste plus qu'à merge la MR.

2019-04-03 20:24 UTC, ConorRyan requested changes
Quasi parfait, juste un petit oubli :)

2019-04-03 20:24 UTC, ConorRyan commented on src/control/sg/MemberInscriptionController.ts
> +      if (result && result.location) {
Attention, ici si la condition est fausse ça fait attendre le serveur pour rien avant de timeout (il me semble). Vaut mieux un 
```
else {
 next(new HttpError(500, "error descrip");
}
```

2019-04-03 20:24 UTC, ConorRyan commented on src/control/sg/MemberInscriptionController.ts
> +      if (result && result.location) {
idem

2019-04-03 20:24 UTC, ConorRyan commented on views/sg/inscription/members/viewAll.hbs
> +  {{> template/sidebar}}
BG !

2019-04-03 20:24 UTC, ConorRyan commented on views/sg/inscription/members/viewInscription.hbs
> +                        <div class="panel panel-default">
Nice !

2019-04-04 17:22 UTC, merged