Add registration for consultants
ETICINSATechnologies/Keros-Front pull request #84
Opened 2019-04-28 15:47 UTC by ubrg

- Ajout de l'inscription des consultants. (modèles, contrôleur, services)
- Ajout d'un outil pour extraire les fichiers d'une requête http et les sérialiser. (base64)
- Ajout des vues pour afficher toutes les inscriptions en cours et le détail d'une inscription.
- Ajout d'inscriptions mock.

2019-04-28 19:08 UTC, vdevulder1 requested changes
Il doit y avoir des problèmes avec les files. Dès qu'il y en a, il y a un problème pour `Submit`. Typiquement on ne peut pas édtier puis valider derrière car rien ne se passe. Et ça le fait que quand il y a des documents dans les inscriptions concernées. Ce qui est bizarre c'est que ça le fait également pour les inscriptions membres et j'ai eu beau cherché j'ai pas trouvé d'où ça pouvait venir pour l'instant.

2019-04-28 19:08 UTC, vdevulder1 commented on src/models/sg/ConsultantInscription.ts
> +        private lastName ?: string,
Il manque les champs `genderId` et `birthday` . Je pense que c'est parce qu'ils ont été rajoutés récemment dans l'API.

2019-04-28 19:08 UTC, vdevulder1 commented on src/models/sg/ConsultantInscriptionCreateRequest.ts
> +        public firstName ?: string,
Idem que pour `ConsultantInscription`

2019-04-28 19:08 UTC, vdevulder1 commented on src/control/sg/consultantInscriptionRouter.ts
> +    router.post("postform", inscriptionController.postConsultantInscriptionForm);
pour le `post`, la bonne route est `"/postform"` sinon ça ne fonctionne pas. Néanmoins en cherchant d'où ça venait je me suis aperçu que c'était de ma faute parce que dans le router de `MemberInscription` y a la même erreur. Donc désolé! Et si tu pouvais modifier ça dans les deux routers du coup ça serait top.

2019-04-28 19:08 UTC, vdevulder1 commented on src/control/sg/ConsultantInscriptionController.ts
> +        inscriptionRequest.lastName = req.body.lastName;
Toujours lié aux nouveaux champs il va falloir les ajouter ici

2019-04-28 19:08 UTC, vdevulder1 commented on src/control/sg/ConsultantInscriptionController.ts
> +            DepartmentService.getAllDepartments(function (err1, departments: Department[] | null) {
Il va falloir récupérer les `Genders` ici pour la sélection du `genderId` (voir suite si jamais). Et les intégrer à chaque fois que c'est nécessaire

2019-04-28 19:08 UTC, vdevulder1 commented on src/control/sg/ConsultantInscriptionController.ts
> +            res.redirect("sg/consultant-inscription");
Il faut redirect vers `/sg/consultant-inscription` - encore une erreur de ma part, désolé. Il faudrait modifier pour l'inscription membre également.

2019-05-01 15:39 UTC, ubrg commented on src/models/sg/ConsultantInscriptionCreateRequest.ts
> +        public firstName ?: string,
Ajouté, pour les inscriptions membres aussi.

2019-05-01 15:39 UTC, ubrg commented on src/models/sg/ConsultantInscription.ts
> +        private lastName ?: string,
Ajouté, pour les inscriptions membres aussi.

2019-05-01 15:40 UTC, ubrg commented on src/control/sg/consultantInscriptionRouter.ts
> +    router.post("postform", inscriptionController.postConsultantInscriptionForm);
C'est corrigé pour les deux routers.

2019-05-01 15:40 UTC, ubrg commented on src/control/sg/ConsultantInscriptionController.ts
> +        inscriptionRequest.lastName = req.body.lastName;
Ajouté, pour les inscriptions membres aussi.

2019-05-01 15:41 UTC, ubrg commented on src/control/sg/ConsultantInscriptionController.ts
> +            DepartmentService.getAllDepartments(function (err1, departments: Department[] | null) {
Récupération et utilisation dans la view ajoutées, pour les inscriptions membres aussi.

2019-05-01 15:41 UTC, ubrg commented on src/control/sg/ConsultantInscriptionController.ts
> +            res.redirect("sg/consultant-inscription");
C'est fait pour les deux controllers.

2019-05-01 17:39 UTC, vdevulder1 approved these changes

2019-05-01 17:43 UTC, merged